In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from  sklearn.model_selection import train_test_split
import seaborn as sns

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
sqewness = df.skew()
print(sqewness)

Pregnancies                 0.901674
Glucose                     0.173754
BloodPressure              -1.843608
SkinThickness               0.109372
Insulin                     2.272251
BMI                        -0.428982
DiabetesPedigreeFunction    1.919911
Age                         1.129597
Outcome                     0.635017
dtype: float64


In [6]:
kurtosis = df.kurt()
print(kurtosis)

Pregnancies                 0.159220
Glucose                     0.640780
BloodPressure               5.180157
SkinThickness              -0.520072
Insulin                     7.214260
BMI                         3.290443
DiabetesPedigreeFunction    5.594954
Age                         0.643159
Outcome                    -1.600930
dtype: float64


In [7]:
X = df.iloc[:,: -1]
Y = df.iloc[:, -1]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
# lets do classification


x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=1/3)

In [9]:


lr = LogisticRegression()
pred = lr.fit(x_train, y_train)

C:\Users\atkumar\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
pred = lr.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print (accuracy_score(y_test, pred))
print (precision_score(y_test, pred, average='macro'))
print (recall_score(y_test, pred, average='macro'))
print (f1_score(y_test, pred, average='macro'))

0.7734375
0.7534290271132377
0.7173734610123119
0.7286549707602339


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       170
           1       0.71      0.55      0.62        86

    accuracy                           0.77       256
   macro avg       0.75      0.72      0.73       256
weighted avg       0.77      0.77      0.76       256



In [13]:
lr.coef_

array([[ 0.1197929 ,  0.02943886, -0.00908337, -0.00419376, -0.00228537,
         0.06525806,  1.65333734,  0.00625616]])

In [14]:
lr.intercept_

array([-6.94906822])

In [15]:
lr.classes_

array([0, 1], dtype=int64)

#    Decision Tree Model

In [16]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz, ExtraTreeClassifier

In [17]:
dt = DecisionTreeClassifier(criterion='entropy')

In [18]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y, test_size=1/3)

In [19]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy')

In [20]:
dtPred = dt.predict(xtest)

In [21]:
export_graphviz(dt,'dt.tree')

In [22]:
from sklearn.metrics import classification_report
print(classification_report(ytest, dtPred))

              precision    recall  f1-score   support

           0       0.80      0.81      0.81       166
           1       0.65      0.63      0.64        90

    accuracy                           0.75       256
   macro avg       0.73      0.72      0.72       256
weighted avg       0.75      0.75      0.75       256



In [23]:
dt.feature_importances_

array([0.05950722, 0.28855077, 0.06521208, 0.06219871, 0.05555008,
       0.16413849, 0.17424309, 0.13059955])

#    Random Forest Model

In [24]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf=RandomForestClassifier(n_estimators=100)

In [26]:
xtrain_rf, xtest_rf, ytrain_rf, ytest_rf = train_test_split(X,Y, test_size=1/3)

In [27]:
rf.fit(xtrain_rf,ytrain_rf)

RandomForestClassifier()

In [28]:
predRF = rf.predict(xtest_rf)

In [29]:
from sklearn.metrics import classification_report
print(classification_report(ytest_rf, predRF))

              precision    recall  f1-score   support

           0       0.76      0.87      0.81       160
           1       0.72      0.55      0.62        96

    accuracy                           0.75       256
   macro avg       0.74      0.71      0.72       256
weighted avg       0.75      0.75      0.74       256

